---
clone:
  depth: 1
kind: pipeline
name: bullseye 386 build
platform:
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh bullseye debian 386 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: build
  when:
    event:
    - push
- commands:
  - ./ci/scripts/build.sh bullseye debian 386 ${DRONE_TAG} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: release
  when:
    event:
    - tag
- commands:
  - ./ci/scripts/publish.sh bullseye debian 386 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: copy build
  volumes:
  - name: zerotier-builds
    path: /zerotier-builds
  when:
    event:
    - push
- commands:
  - ./ci/scripts/publish.sh bullseye debian 386 ${DRONE_TAG} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: copy relase
  volumes:
  - name: zerotier-releases
    path: /zerotier-releases
  when:
    event:
    - tag
trigger:
  event:
  - push
  - tag
  - custom
type: docker
volumes:
- host:
    path: /zerotier-builds
  name: zerotier-builds
- host:
    path: /zerotier-releases
  name: zerotier-releases
---
clone:
  depth: 1
kind: pipeline
name: bullseye armv7 build
platform:
  arch: arm64
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh bullseye debian armv7 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: build
  when:
    event:
    - push
- commands:
  - ./ci/scripts/build.sh bullseye debian armv7 ${DRONE_TAG} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: release
  when:
    event:
    - tag
- commands:
  - ./ci/scripts/publish.sh bullseye debian armv7 100.0.0+${DRONE_COMMIT_SHA:0:8}
    ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: copy build
  volumes:
  - name: zerotier-builds
    path: /zerotier-builds
  when:
    event:
    - push
- commands:
  - ./ci/scripts/publish.sh bullseye debian armv7 ${DRONE_TAG} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: copy relase
  volumes:
  - name: zerotier-releases
    path: /zerotier-releases
  when:
    event:
    - tag
trigger:
  event:
  - push
  - tag
  - custom
type: docker
volumes:
- host:
    path: /zerotier-builds
  name: zerotier-builds
- host:
    path: /zerotier-releases
  name: zerotier-releases
---
clone:
  depth: 1
kind: pipeline
name: bullseye amd64 build
platform:
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh bullseye debian amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: build
  when:
    event:
    - push
- commands:
  - ./ci/scripts/build.sh bullseye debian amd64 ${DRONE_TAG} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: release
  when:
    event:
    - tag
- commands:
  - ./ci/scripts/publish.sh bullseye debian amd64 100.0.0+${DRONE_COMMIT_SHA:0:8}
    ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: copy build
  volumes:
  - name: zerotier-builds
    path: /zerotier-builds
  when:
    event:
    - push
- commands:
  - ./ci/scripts/publish.sh bullseye debian amd64 ${DRONE_TAG} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: copy relase
  volumes:
  - name: zerotier-releases
    path: /zerotier-releases
  when:
    event:
    - tag
trigger:
  event:
  - push
  - tag
  - custom
type: docker
volumes:
- host:
    path: /zerotier-builds
  name: zerotier-builds
- host:
    path: /zerotier-releases
  name: zerotier-releases
---
clone:
  depth: 1
kind: pipeline
name: bullseye arm64 build
platform:
  arch: arm64
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh bullseye debian arm64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: build
  when:
    event:
    - push
- commands:
  - ./ci/scripts/build.sh bullseye debian arm64 ${DRONE_TAG} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: release
  when:
    event:
    - tag
- commands:
  - ./ci/scripts/publish.sh bullseye debian arm64 100.0.0+${DRONE_COMMIT_SHA:0:8}
    ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: copy build
  volumes:
  - name: zerotier-builds
    path: /zerotier-builds
  when:
    event:
    - push
- commands:
  - ./ci/scripts/publish.sh bullseye debian arm64 ${DRONE_TAG} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: copy relase
  volumes:
  - name: zerotier-releases
    path: /zerotier-releases
  when:
    event:
    - tag
trigger:
  event:
  - push
  - tag
  - custom
type: docker
volumes:
- host:
    path: /zerotier-builds
  name: zerotier-builds
- host:
    path: /zerotier-releases
  name: zerotier-releases
---
clone:
  depth: 1
depends_on:
- bullseye 386 build
- bullseye armv7 build
- bullseye amd64 build
- bullseye arm64 build
kind: pipeline
name: bullseye index
platform:
  os: linux
pull: always
steps:
- commands:
  - /usr/local/bin/index zerotier-builds debian bullseye 386 armv7 amd64 arm64
  environment:
    GPG_PRIVATE_KEY:
      from_secret: gpg-private-key
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/apt-builder
  name: index build
  volumes:
  - name: zerotier-builds
    path: /zerotier-builds
  when:
    event:
    - push
- commands:
  - /usr/local/bin/index zerotier-releases debian bullseye 386 armv7 amd64 arm64
  environment:
    GPG_PRIVATE_KEY:
      from_secret: gpg-private-key
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/apt-builder
  name: index release
  volumes:
  - name: zerotier-releases
    path: /zerotier-releases
  when:
    event:
    - tag
trigger:
  event:
  - push
  - tag
  - custom
type: docker
volumes:
- host:
    path: /zerotier-builds
  name: zerotier-builds
- host:
    path: /zerotier-releases
  name: zerotier-releases
---
clone:
  depth: 1
depends_on:
- bullseye index
kind: pipeline
name: bullseye 386 test
platform:
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/test.sh bullseye debian 386 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: test build
  volumes:
  - name: zerotier-builds
    path: /zerotier-builds
  when:
    event:
    - push
- commands:
  - ./ci/scripts/test.sh bullseye debian 386 ${DRONE_TAG} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: test release
  volumes:
  - name: zerotier-releases
    path: /zerotier-releases
  when:
    event:
    - tag
trigger:
  event:
  - push
  - tag
  - custom
type: docker
volumes:
- host:
    path: /zerotier-builds
  name: zerotier-builds
- host:
    path: /zerotier-releases
  name: zerotier-releases
---
clone:
  depth: 1
depends_on:
- bullseye index
kind: pipeline
name: bullseye armv7 test
platform:
  arch: arm64
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/test.sh bullseye debian armv7 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: test build
  volumes:
  - name: zerotier-builds
    path: /zerotier-builds
  when:
    event:
    - push
- commands:
  - ./ci/scripts/test.sh bullseye debian armv7 ${DRONE_TAG} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: test release
  volumes:
  - name: zerotier-releases
    path: /zerotier-releases
  when:
    event:
    - tag
trigger:
  event:
  - push
  - tag
  - custom
type: docker
volumes:
- host:
    path: /zerotier-builds
  name: zerotier-builds
- host:
    path: /zerotier-releases
  name: zerotier-releases
---
clone:
  depth: 1
depends_on:
- bullseye index
kind: pipeline
name: bullseye amd64 test
platform:
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/test.sh bullseye debian amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: test build
  volumes:
  - name: zerotier-builds
    path: /zerotier-builds
  when:
    event:
    - push
- commands:
  - ./ci/scripts/test.sh bullseye debian amd64 ${DRONE_TAG} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: test release
  volumes:
  - name: zerotier-releases
    path: /zerotier-releases
  when:
    event:
    - tag
trigger:
  event:
  - push
  - tag
  - custom
type: docker
volumes:
- host:
    path: /zerotier-builds
  name: zerotier-builds
- host:
    path: /zerotier-releases
  name: zerotier-releases
---
clone:
  depth: 1
depends_on:
- bullseye index
kind: pipeline
name: bullseye arm64 test
platform:
  arch: arm64
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/test.sh bullseye debian arm64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: test build
  volumes:
  - name: zerotier-builds
    path: /zerotier-builds
  when:
    event:
    - push
- commands:
  - ./ci/scripts/test.sh bullseye debian arm64 ${DRONE_TAG} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: test release
  volumes:
  - name: zerotier-releases
    path: /zerotier-releases
  when:
    event:
    - tag
trigger:
  event:
  - push
  - tag
  - custom
type: docker
volumes:
- host:
    path: /zerotier-builds
  name: zerotier-builds
- host:
    path: /zerotier-releases
  name: zerotier-releases
---
kind: signature
hmac: 887a3ef78d3fe8f0149911e1e4876401dd7dd313b36eb893e791fa42f45d7768

...
